apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep
  namespace: mohammedalghamdi-tawazun
  labels:
    app: mysql
    name: MohammedAlghamdi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mohammed1234
        - name: MYSQL_DATABASE
          value: tawazun-db
        - name: MYSQL_ROOT_USER
          value: root

        ports:
        - containerPort: 3306
          name: mysql

        volumeMounts:
        - name:  mysql-storage
          mountPath: /var/lib/mysql  
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          exec:
            command:
              - bash
              - "-c"
              - |
                mysqladmin -uroot -p$MYSQL_ROOT_PASSWORD ping &> /dev/null
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          failureThreshold: 30
          periodSeconds: 10
          
      volumes: 
      - name: mysql-storage
        persistentVolumeClaim:
          claimName:  mysql-pvc


          
      

   