apiVersion: apps/v1
kind: Deployment
metadata:
  name: tawazun-deployment
  namespace: mohammedalghamdi-tawazun
  labels:
    app: tawazun
    name: MohammedAlghamdi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tawazun
      service: tawazun-svc
  template:
    metadata:
      name: tawazun
      labels:
        app: tawazun
        service: tawazun-svc
    spec:
      containers:
      - name: tawazun
        image: mhutatah/tawazun:latest

        ports:
        - containerPort: 8080

        env:
        - name: DB_URL
          value: mysql-svc 
        - name: DB_PORT
          value: '3306'
        - name: DB_NAME
          value: tawazun-db
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: mohammed1234
        
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "4"
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 60
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 130
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 140
          periodSeconds: 10

        