apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: mohammedalghamdi-tawazun
  labels:
    app: mysql
    name: MohammedAlghamdi
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/lab"
